kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: my-nodejs
          image: nodejs-image:latest
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            limits:
              ephemeral-storage: 150Mi
              cpu: '15m'
              memory: 60Mi
            requests:
              ephemeral-storage: 100Mi
              cpu: '10m'
              memory: 50Mi
          env:
          - name: http_proxy
            value: 'http://proxy01.hslu.ch:8080'
          - name: https_proxy
            value: 'http://proxy01.hslu.ch:8080'
          - name: no_proxy
            value: 'localhost,127.0.0.1,.campus.intern,.hslu.ch'
---
kind: Service
apiVersion: v1
metadata:
  name: my-nodejs-svc
spec:
  ports:
    - name: http-3001
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: nodejs-app